import Head from 'next/head'
import Navigation from '../komponenten/Navigation'
import Fusszeile from '../komponenten/Fusszeile'

export default function Layout({ children }) {
    return (
        <div>
            <Head>
                <title>LieferEx - Dein Lieferservice</title>
                <meta name="description" content="Generated by virtualdev.de" />
                <link rel="icon" href="bilder/favicon2.ico" />
            </Head>
            <Navigation />
            <div className='container'>
                {children}
            </div>
            <Fusszeile />
        </div>
    )
}